### ISSUE TITLE
Keep on getting 0x1 Error

### ISSUE THREAD

**Issue by GitBolt** [MonacoProtocol/sdk#111]
hey guys. i'm getting balance not enough error. 
this is the full response:
```
  success: false,
  errors: [
    SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1
        at Connection._callee89$ (/home/bolt/Desktop/disbet/node_modules/@solana/web3.js/lib/index.cjs.js:12412:21)
        at tryCatch (/home/bolt/Desktop/disbet/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:45:16)
        at Generator.<anonymous> (/home/bolt/Desktop/disbet/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:133:17)
        at Generator.next (/home/bolt/Desktop/disbet/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:74:21)
        at asyncGeneratorStep (/home/bolt/Desktop/disbet/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
        at _next (/home/bolt/Desktop/disbet/node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
      logs: [Array],
      programErrorStack: [ProgramErrorStack]
    }
  ],
  data: {
    orderPk: PublicKey [PublicKey(6zqj7m6XAZUf4qe64R3asAnTmKb3rwR8m9pbHFAmt6Yh)] {
      _bn: <BN: 591ba2b559b083662753335533ebf2c297f278c3956f167a0b11d617d801b7ba>
    },
    tnxID: undefined
  }
}
```
i do have sufficient USDT balance in my wallet.
this is my function that is raising issue:

```typescript
    const program = await getProgram(new PublicKey('monacoUXKtUi6vKsQwaLyxmXKSievfNWEcYXTgkbCih'), sk);

    const marketData = await getMarket(program, new PublicKey(marketPk))
    const mintInfo = await getMintInfo(program, marketData.data.account.mintAccount)
    const stakeInteger = new BN(amount * 10 ** mintInfo.data.decimals);
    let marketPricesData = await getMarketOutcomePriceData(program, new PublicKey(marketPk));

    if (!marketPricesData || !marketData.success) {
        return undefined
    }

    try {
        const data = await createOrder(
            program,
            new PublicKey(marketPk),
            marketPricesData.marketOutcomeIndex,
            type == "for" ? true : false,
            type == "for" ? marketPricesData.forOutcomePrice : marketPricesData.againstOutcomePrice,
            stakeInteger
        );

        console.log("Order Res: ", data)
        return { data, marketPricesData }
    } catch (e: any) {
        console.log("Error creating order: ", e.errors.toString())
        return { error: true, data: e.toString() }
    }
 ```

**Comment by GitBolt** [comment]
nevermind, i'm dumb. had a different issue showing up when i didn't have enough sol, this time i thought its related to me not having enough USDT tokens, but apparently it was SOL too. added more balance to my wallet and it worked.
